### ISSUE TITLE
Parent POM for org.jboss.spec.javax.servlet.jboss-servlet-api_3.0_spec:1.0.2.Final-redhat-2 does not exist in the repo

### ISSUE THREAD

**Issue by mwhidden** [jboss-developer/jboss-developer-shared-resources#85]
This POM 
http://maven.repository.redhat.com/techpreview/all/org/jboss/spec/javax/servlet/jboss-servlet-api_3.0_spec/1.0.2.Final-redhat-2/jboss-servlet-api_3.0_spec-1.0.2.Final-redhat-2.pom

refers to a parent org.jboss:jboss-parent:9 pom which does not exist in the repo.

**Comment by sgilda** [comment]
I'm not clear that this issue belongs here. Maybe here: https://github.com/jboss-developer/jboss-eap-boms ?

I need to investigate.

Thanks!

**Comment by mwhidden** [comment]
I'm not clear either. Sorry -- very new. Happy to move it to where it belongs.

**Comment by rafabene** [comment]
Indeed. This issue doesn't pertence here but I also don't know where this issue should land. @pgier might have a clue since it's related to the productized bom. The upstream version is kept here: https://github.com/jboss/jboss-servlet-api_spec

Btw, the right parent should be: org.jboss:jboss-parent:9-redhat-1 instead.

Thanks for reporting it @mwhidden

**Comment by sgilda** [comment]
Thanks @rafabene !

@mwhidden : Where do you see this issue manifest itself? In other words, what do I need to do to recreate this issue? That may help. :-)

**Comment by mwhidden** [comment]
I came across while trying to build the helloworld project in the jboss quickstarts. the build failed because it had a dependency on org.jboss.spec.javax:servlet.jboss-servlet-api_3.0_spec:1.0.2.Final-redhat-2 which in turn depends on org.jboss:jboss-parent:9, which does not exist.

**Comment by sgilda** [comment]
@mwhidden : I'm not clear that you are building the correct version of the quickstarts. Did you follow the instructions here: https://github.com/jboss-developer/jboss-developer-shared-resources/blob/master/guides/CONTRIBUTING.md ?

Are you checkout out from the '7.0.x-develop' branch here: https://github.com/jboss-developer/jboss-eap-quickstarts?

You should not be checking out the 7.0.x branch because you need artifacts from a Maven repository that is not available yet.

**Comment by pgier** [comment]
The jboss-parent pom version 9 is in Maven central here:
http://central.maven.org/maven2/org/jboss/jboss-parent/9/

Maven central is available to a default Maven install, but maybe you have some mirror/repository settings that are not allowing access to central?

**Comment by rafabene** [comment]
@pgier Shouldn't the whole chain of parent poms refer to product versions?

**Comment by pgier** [comment]
@rafabene Not necessarily.  We normally only do that with thirdparty (non JBoss) projects because those parent POMs have different settings than what we want.  There is not much difference between the community jboss-parent pom and the -redhat ones.

**Comment by rafabene** [comment]
Ok.

Thanks

On Fri, Feb 26, 2016 at 10:29 AM, Paul Gier <notifications@github.com>
wrote:

> @rafabene <https://github.com/rafabene> Not necessarily. We normally only
> do that with thirdparty (non JBoss) projects because those parent POMs have
> different settings than what we want. There is not much difference between
> the community jboss-parent pom and the -redhat ones.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jboss-developer/jboss-developer-shared-resources/issues/85#issuecomment-189323100>
> .
>



-- 
*Rafael Benevides | Senior Software Engineer*
JBoss Developer Materials lead
M: +1-919-592-6255



Better technology. Faster innovation. Powered by community collaboration.
See how it works at www.redhat.com

**Comment by sgilda** [comment]
Can I close this issue?

**Comment by rafabene** [comment]
From me, yes!

On Fri, Feb 26, 2016 at 10:46 AM, sgilda <notifications@github.com> wrote:

> Can I close this issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jboss-developer/jboss-developer-shared-resources/issues/85#issuecomment-189331825>
> .
>



-- 
*Rafael Benevides | Senior Software Engineer*
JBoss Developer Materials lead
M: +1-919-592-6255



Better technology. Faster innovation. Powered by community collaboration.
See how it works at www.redhat.com

**Comment by mwhidden** [comment]
I see. For the environment that was being tested, access to Maven Central is blocked. I assumed the quickstarts were self-contained. We'll manually modify the POMs to override the dependencies on Maven Central.

**Comment by sgilda** [comment]
@pgier and @rafabene : Thanks for helping out with this!

Closing the issue.
